###
GET http://localhost:8080/rest/swagger.json
###
GET http://localhost:8080/rest/posts/5
###
GET http://localhost:8080/rest/posts?count=10&page=0&limitcontent=3
###
GET http://localhost:8080/rest/posts/5/comments
###
GET http://localhost:8080/rest/users?name=qualcuno

###

POST http://localhost:8080/rest/auth/login
Content-Type: text/plain

Plut0;ploto

### remember to insert the Authorization token once obtained

POST  http://localhost:8080/rest/posts
Content-type: application/json
Authorization: 

{
    "title" : "Un nuovo post",
    "content" : "yadda yadda yadda yadda yadda"
}

###

POST http://localhost:8080/rest/users/
Content-Type: application/json
Password: P@ssw0rd

{
    "username" : "i_use_bad_password",
    "email" : "stupid@us.er"
} 