###

GET http://localhost:8080/rest/post/5

###

GET http://localhost:8080/rest/post?count=10&page=0&limitcontent=3

###

GET http://localhost:8080/rest/post/5/comments

###

GET http://localhost:8080/rest/user?name=qualcuno

###

POST  http://localhost:8080/rest/user
content-type: application/json

{
    "username" : "qualcuniche",
    "email" : "qualche@cuno.com"
}